### ISSUE TITLE
At symbols embedded in local parts prevent checking

### ISSUE THREAD

**Issue by Y-Less** [signupper/emali#1]
https://emali.signupper.net/api/email-typo-check/?email="hi@there"@gmali.com

Returns result OK, should probably return `suggestion: "hi@there"@gmail.com`.  Without the embedded `@`, it seems to handle the full range of local parts quite well, which is good.

**Comment by koliber** [comment]
The API has been fixed to correctly deal with 1 or more @'s in the local part of the email address. The fix is live.
